name: Build and Upload Jar

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Generate JAR file
        run: mvn package --file pom.xml --batch-mode
      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/*.jar
